//! Window icon, generated by `tools/make_icon.py`.

/// Raw RGBA, top-down, 64x64.
const RGBA: &[u8] = include_bytes!("../assets/icon.rgba");
const SIZE: u32 = 64;

pub fn data() -> eframe::egui::IconData {
    eframe::egui::IconData {
        rgba: RGBA.to_vec(),
        width: SIZE,
        height: SIZE,
    }
}
